/**
 * Movies API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FastEndpointsProblemDetailsError } from './fast-endpoints-problem-details-error';


export interface FastEndpointsProblemDetails { 
    type?: string;
    title?: string;
    status?: number;
    instance?: string;
    traceId?: string;
    detail?: string | null;
    errors?: Array<FastEndpointsProblemDetailsError>;
}

