/**
 * Movies API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FastEndpointsProblemDetailsError { 
    name?: string;
    reason?: string;
    code?: string | null;
    severity?: string | null;
}

