/**
 * Movies API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoviesApiUseCasesMoviesMovieSummaryDto } from './movies-api-use-cases-movies-movie-summary-dto';


export interface MoviesApiApiEndpointsMoviesListListMoviesResponse { 
    items?: Array<MoviesApiUseCasesMoviesMovieSummaryDto>;
    totalItems?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    hasPrevious?: boolean;
    hasNext?: boolean;
}

