/**
 * Movies API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoviesApiCoreMoviesAggregateMovieId } from './movies-api-core-movies-aggregate-movie-id';
import { MoviesApiSharedKernelDtosLookupDto } from './movies-api-shared-kernel-dtos-lookup-dto';


export interface MoviesApiApiEndpointsMoviesGetGetMovieResponse { 
    id?: MoviesApiCoreMoviesAggregateMovieId;
    showId?: string;
    title?: string;
    type?: string;
    directors?: Array<MoviesApiSharedKernelDtosLookupDto>;
    cast?: Array<MoviesApiSharedKernelDtosLookupDto>;
    countries?: Array<MoviesApiSharedKernelDtosLookupDto>;
    dateAdded?: string;
    releaseYear?: number;
    rating?: string;
    duration?: string;
    genres?: Array<MoviesApiSharedKernelDtosLookupDto>;
    description?: string;
}

