/**
 * Movies API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MoviesApiUseCasesMoviesMovieSummaryDto { 
    id?: number;
    showId?: string;
    title?: string;
    type?: string;
    genres?: Array<string>;
    rating?: string;
    duration?: string;
}

